var searchData=
[
  ['scope_5fexit_0',['scope_exit',['../structetl_1_1scope__exit.html',1,'etl']]],
  ['sequenced_5fpolicy_1',['sequenced_policy',['../structetl_1_1execution_1_1sequenced__policy.html',1,'etl::execution']]],
  ['simd_2',['simd',['../structetl_1_1experimental_1_1parallelism__v2_1_1simd.html',1,'simd&lt; T, Abi &gt;'],['../structetl_1_1experimental_1_1parallelism__v2_1_1simd.html',1,'simd&lt; T, Abi &gt;']]],
  ['simd_5fmask_3',['simd_mask',['../structetl_1_1experimental_1_1parallelism__v2_1_1simd__mask.html',1,'simd_mask&lt; T, Abi &gt;'],['../structetl_1_1experimental_1_1parallelism__v2_1_1simd__mask.html',1,'simd_mask&lt; T, Abi &gt;']]],
  ['simd_5fsize_4',['simd_size',['../structetl_1_1experimental_1_1parallelism__v2_1_1simd__size.html',1,'simd_size&lt; T, Abi &gt;'],['../structetl_1_1experimental_1_1parallelism__v2_1_1simd__size.html',1,'simd_size&lt; T, Abi &gt;']]],
  ['small_5fptr_5',['small_ptr',['../structetl_1_1small__ptr.html',1,'etl']]],
  ['sorted_5funique_5ft_6',['sorted_unique_t',['../structetl_1_1sorted__unique__t.html',1,'etl']]],
  ['source_5flocation_7',['source_location',['../structetl_1_1source__location.html',1,'etl']]],
  ['span_8',['span',['../structetl_1_1span.html',1,'etl']]],
  ['span_3c_20etl_3a_3abasic_5fformat_5farg_3c_20context_20_3e_20const_20_3e_9',['span&lt; etl::basic_format_arg&lt; Context &gt; const &gt;',['../structetl_1_1span.html',1,'etl']]],
  ['span_3c_20etl_3a_3abyte_20_3e_10',['span&lt; etl::byte &gt;',['../structetl_1_1span.html',1,'etl']]],
  ['stack_11',['stack',['../structetl_1_1stack.html',1,'etl']]],
  ['static_5fset_12',['static_set',['../structetl_1_1static__set.html',1,'etl']]],
  ['static_5fvector_13',['static_vector',['../structetl_1_1static__vector.html',1,'etl']]],
  ['static_5fvector_3c_20key_2c_20capacity_20_3e_14',['static_vector&lt; Key, Capacity &gt;',['../structetl_1_1static__vector.html',1,'etl']]],
  ['stream_5fbuffer_15',['stream_buffer',['../structetl_1_1experimental_1_1freertos_1_1stream__buffer.html',1,'etl::experimental::freertos']]],
  ['strided_5fslice_16',['strided_slice',['../structetl_1_1strided__slice.html',1,'etl']]],
  ['string_5fconstant_17',['string_constant',['../structetl_1_1string__constant.html',1,'etl']]],
  ['strong_5fordering_18',['strong_ordering',['../structetl_1_1strong__ordering.html',1,'etl']]],
  ['submdspan_5fmapping_5fresult_19',['submdspan_mapping_result',['../structetl_1_1submdspan__mapping__result.html',1,'etl']]],
  ['suspend_5falways_20',['suspend_always',['../structetl_1_1suspend__always.html',1,'etl']]],
  ['suspend_5fnever_21',['suspend_never',['../structetl_1_1suspend__never.html',1,'etl']]],
  ['system_5fclock_22',['system_clock',['../structetl_1_1chrono_1_1system__clock.html',1,'etl::chrono']]]
];
